included:
  - Packages
  - Apps

excluded:
  - .build
  - DerivedData

line_length:
  warning: 140
  error: 180

identifier_name:
  min_length:
    warning: 2

force_cast: error
force_try: error

trailing_whitespace: error
empty_count: warning
